### ISSUE TITLE
the use of ENTRYPOINT make this image useless

### ISSUE THREAD

**Issue by cpu100** [bitnami/bitnami-docker-kubectl#10]
In general, we need to execute additional shell commands before and after the kubectl command. eg, get the full name of pod.

The use of ENTRYPOINT make this image useless.

**Comment by marcosbc** [comment]
@cpu100 Could you describe more on the issue you're facing?

Note that with the current entrypoint configuration, if you run something like the below you would be running `kubectl version`:

```bash
$ docker run -ti bitnami/kubectl version
```

Changing the entrypoint would be for running a command different "kubectl" (i.e. Bash), and we believe this image is meant only to be a Docker wrapper for Kubectl.

Could you be referring to problems connecting to the Kubernetes API server? Beware of the section [Loading your own configuration](https://github.com/bitnami/bitnami-docker-kubectl#loading-your-own-configuration) in the README.

**Comment by cpu100** [comment]
Thank you marcosbc.
A scene like this, but it's done.

**K8s CronJob**
```
apiVersion: batch/v1beta1
kind: CronJob
metadata:
  name: certbot-renew
spec:
  schedule: "41 5 * * 2,4,6"
  concurrencyPolicy: Forbid
  jobTemplate:
    spec:
      template:
        spec:
          volumes:
            - name: kube-config
              hostPath:               
                path: /root/.kube/config
          restartPolicy: Never
          containers:
            - name: job
              image: local/kubectl:1.17.3
              imagePullPolicy: IfNotPresent
              volumeMounts:
                - mountPath: /root/.kube/config
                  name: kube-config
              args:
                - sh
                - -c
                - pod=$(kubectl get pod --selector app=nginx --output jsonpath={.items[0].metadata.name});
                  kubectl exec $pod -- certbot renew --renew-hook='nginx -s reload';


```

**Dockerfile**
```
FROM busybox

ARG KUBE_VER=v1.17.3

RUN cd /bin && \
    wget https://storage.googleapis.com/kubernetes-release/release/$KUBE_VER/bin/linux/amd64/kubectl && \
    chmod +x kubectl
```
