### ISSUE TITLE
Kubernetes Documentation

### ISSUE THREAD

**Issue by techdragon** [bitnami/bitnami-docker-kubectl#14]
**Description**

Documentation for usage in a Kubernetes environment.

It would be very useful if there was documentation on how to use this in a Kubernetes environment. People appear to have had issues in the past #10 and since this is one of the most popular and continuously updated kubectl containers, it seems sensible to have some basic documentation to cover this use case.

**Comment by andresbono** [comment]
Hi @techdragon, thanks for opening this issue. Do you think that adding an example of usage of the container in a k8s manifest (pod, deployment...) in the README.md would be useful?

By the way, we are open to receive and review PRs! Feel free to open one if you want.

**Comment by techdragon** [comment]
Documentation in the README.md is pretty much what I was hoping for, this container is simple enough it shouldnt really end up needing more than a paragraph or two of explanation plus the example yaml. For the examples I'd recommend a plain pod manifest  for simplicity and a job or cron job manifest to show a more realistic scenario that users will probably be picturing before they start looking for a minimal container specifically for running `kubectl`. 😄 

I ended up rolling my own for a couple of reasons. Firstly I found myself in the same position as the author of #10 did, which in hindsight I can see a way around, but at the time without the ability to connect to the pod and debug the current state I was unable to progress. Secondly, my environment is an AWS EKS cluster and it seemed useful to pin my `kubeclt` binary to one of the ones provided as officially supported with my cluster version by AWS. 

But the results of my efforts are probably transferrable over to an initcontainer based approach. 
If I have time I might be able to draft something more complete and issue a PR, but for now, in case anyone else wants to experiment.

These steps are necessary for connecting to a service account for generic internal Kubernetes API authentication, `kubectl get pods` and similar commands should work, but more complex security hardening/situations. probably wont work eg: requiring external authentication using GKE, AKS, EKS cloud credentials.

```bash
kubectl config set-cluster "${K8S_CLUSTER_NAME:-default}" \
    --server="https://${KUBERNETES_SERVICE_HOST}:${KUBERNETES_SERVICE_PORT}" \
    --certificate-authority="/var/run/secrets/kubernetes.io/serviceaccount/ca.crt" \
    --embed-certs=true
kubectl config set-credentials "${K8S_USER_NAME:-default}" \
    --cluster="${K8S_CLUSTER_NAME:-default}" \
    --token="$(cat /var/run/secrets/kubernetes.io/serviceaccount/token)"
kubectl config set-context default \
    --user="${K8S_USER_NAME:-default}" \
    --cluster="${K8S_CLUSTER_NAME:-default}"
kubectl config use-context default
kubectl version
exec "$@"
```
- `K8S_CLUSTER_NAME` and `K8S_USER_NAME` are just optional environment variables for overrides in case I ever need it. 
- The `kubectl version` command at the end is to ensure that I have a valid configuration before any possible `kubectl` command errors that could potentially produce things such as permissions failures that would otherwise be confusing to debug. 

After those commands, are complete, the Kubeconfig file at `/root/.kube/config` is setup so that the currently selected context should work with kubectl out of the box. Getting it all wired up so that the init container(s) do the job of constructing the file like this is the main hurdle.

**Comment by andresbono** [comment]
Thanks for explaining your use case, @techdragon. It would be great to receive a PR from you if you have the time. But as you mention, you comment will benefit other users in the meantime.

**Comment by techdragon** [comment]
Not stale.

**Comment by techdragon** [comment]
Not stale.

**Comment by techdragon** [comment]
Not stale.

**Comment by hectorakemp** [comment]
Not stale.

**Comment by sdlarsen** [comment]
Thanks for documenting it here. Just what I needed :)

**Comment by jketcham** [comment]
I'll throw an example in here of a CronJob that works for me (this is a partial config that gets applied as a patch via kustomize, but the important things are here):

```yaml
apiVersion: batch/v1beta1
kind: CronJob
metadata:
  name: cron-job
  labels:
    type: ops-delete-jobs
spec:
  schedule: "*/5 * * * *" # run every 5 minutes
  jobTemplate:
    spec:
      template:
        spec:
          containers:
          - name: delete-finished-jobs
            image: bitnami/kubectl:1.18
            command:
            - sh
            - "-c"
            - "kubectl get jobs --all-namespaces -l 'type in (your,labels,here)' --field-selector status.successful=1 -o jsonpath=\"{range .items[*]}{.metadata.namespace}{' '}{.metadata.name}{'\\n'}{end}\" | xargs -r -L 1 kubectl delete job --namespace"
```

The key point being to use `sh -c` in the command mainly.

**Comment by ryanpeach** [comment]
Can you give this pod a ClusterRole and a ClusterRoleBinding and expect it to just work for the cluster it is running in (or do you need a kubeconfig file somehow injected into it).

**Comment by jketcham** [comment]
@ryanpeach in my case, a ServiceAccount is created just for this CronJob and it's given a ClusterRole and ClusterRoleBinding to delete Jobs:

```yaml
apiVersion: rbac.authorization.k8s.io/v1
kind: ClusterRole
metadata:
  name: job-cleanup
rules:
- apiGroups: ["batch"]
  resources: ["jobs"]
  verbs: ["list", "delete"]
---
apiVersion: rbac.authorization.k8s.io/v1
kind: ClusterRoleBinding
metadata:
  name: job-cleanup-binding
roleRef:
  apiGroup: rbac.authorization.k8s.io
  kind: ClusterRole
  name: job-cleanup
subjects:
- kind: ServiceAccount
  name: cron-job-sa
```
