### ISSUE TITLE
error: error reading [./nginx.yaml]: recognized file extensions are [.json .yaml .yml]

### ISSUE THREAD

**Issue by webxiaohua** [bitnami/bitnami-docker-kubectl#16]
[nginx.yaml]
```
apiVersion: apps/v1
kind: Deployment
metadata:
  labels:
    app: nginx
  name: nginx-deployment
spec:
  replicas: 1
  selector:
    matchLabels:
      app: nginx
  template:
    metadata:
      labels:
        app: nginx
    spec:
      containers:
      - image: nginx:1.14.0
        name: nginx
      nodeSelector:
        type: nginx
      tolerations:
      - key: "key"
        operator: "Equal"
        value: "nginx"
        effect: "NoSchedule"
```

[cmd]
```
docker run --rm --name kubectl -w /.kube -v /root/.kube/config:/.kube/config -v /root/nginx.yaml:/.kube/nginx.yaml bitnami/kubectl:latest apply -f ./nginx.yaml
```

[error]
error: error reading [./nginx.yaml]: recognized file extensions are [.json .yaml .yml]

[desc]
I try with .yaml、.json and get the same result，I suspect it could be a bug

**Comment by dani8art** [comment]
Hi @webxiaohua I cannot reproduce it, what I've tried is:

**nginx.yaml**

```yaml
apiVersion: apps/v1
kind: Deployment
metadata:
  labels:
    app: nginx
  name: nginx-deployment
spec:
  replicas: 1
  selector:
    matchLabels:
      app: nginx
  template:
    metadata:
      labels:
        app: nginx
    spec:
      containers:
        - image: nginx:1.14.0
          name: nginx
      nodeSelector:
        type: nginx
      tolerations:
        - key: key
          operator: Equal
          value: nginx
          effect: NoSchedule
```

**command**

```console
$ docker run --rm --name kubectl -w /.kube -v ~/.kube/config:/.kube/config -v $(pwd)/nginx.yaml:/.kube/nginx.yaml bitnami/kubectl:latest apply -f ./nginx.yaml
deployment.apps/nginx-deployment created
```
