### ISSUE TITLE
Kubectl config set-context ... results in permission denied

### ISSUE THREAD

**Issue by Jefski14** [bitnami/bitnami-docker-kubectl#19]
**Description**

Hi, we're using the image inside a gitlab-pipeline to automatically restart deployments inside a k8s cluster. Since the gitlab runner has no support for mounting volumes we need a way to change the kubeconfig via script. Excecuting `kubectl config set ...` doesn't work and results in `error: open //.kube/config.lock: permission denied`

How would I go about to setting the kubeconfig without using a docker volume?

**Steps to reproduce the issue:**

`docker run --rm --name kubectl bitnami/kubectl:latest config set-context my-context`

**Describe the results you received:**

`error: open //.kube/config.lock: permission denied`

I excpected to be able to change the config.

**Additional information you deem important (e.g. issue happens only occasionally):**

**Version**

- Output of `docker version`:

```
Client: Docker Engine - Community
 Cloud integration: 1.0.2
 Version:           19.03.13
 API version:       1.40
 Go version:        go1.13.15
 Git commit:        4484c46d9d
 Built:             Wed Sep 16 17:00:27 2020
 OS/Arch:           windows/amd64
 Experimental:      false

Server: Docker Engine - Community
 Engine:
  Version:          19.03.13
  API version:      1.40 (minimum version 1.12)
  Go version:       go1.13.15
  Git commit:       4484c46d9d
  Built:            Wed Sep 16 17:07:04 2020
  OS/Arch:          linux/amd64
  Experimental:     false
 containerd:
  Version:          v1.3.7
  GitCommit:        8fba4e9a7d01810a393d5d25a3621dc101981175
 runc:
  Version:          1.0.0-rc10
  GitCommit:        dc9208a3303feef5b3839f4323d9beb36df0a9dd
 docker-init:
  Version:          0.18.0
  GitCommit:        fec3683
```

**Comment by alemorcuq** [comment]
Hi, @Jefski14.

I don't know if this is what you are trying to do, but according to this (https://docs.gitlab.com/runner/configuration/advanced-configuration.html#example-2-mount-a-host-directory-as-a-data-volume) the GitLab Runner does support volumes.

If that is not a solution for you, I guess you could set the `HOME` environment variable to `/tmp` and that would allow you to write the required files.

**Comment by Jefski14** [comment]
Hi, @alemorcuq.

Thanks for the quick response. This is kind of what I was trying to do but it gets very complicated since our gitlab-runner itself runs inside another docker container. I resulted to just using my own Docker Image thats based on yours but has root as the default user so I can just configure kubectl via commands.

For anyone wondering what I did:
Dockerfile:
```
FROM bitnami/kubectl

USER root
COPY --chown=root config $HOME/.kube/config
ENV KUBECONFIG=$HOME/.kube/config
```
I copy my base kubeconfig with basic settings into the container and set the owner to root so that I can later edit the config via commands.

My gitlab-ci.yml Step to deploy to the configured kubernetes namespace of choice then looks like this:
```
deploy-to-kubernetes:
  stage: deploy
  image:
    name: $KUBERNETES_IMAGE
    entrypoint: [ "" ]
  only:
    - master
  script:
    - kubectl config set-context <context-name> --cluster=<cluster_name> --user=<user_name> --namespace=<namespace_name>
    - kubectl config set current-context <context-name>
    - kubectl rollout restart deployments

```
