### ISSUE TITLE
Can't override entrypoint to use in gitlab-ci

### ISSUE THREAD

**Issue by franck-cussac** [bitnami/bitnami-docker-kubectl#21]
-------------------------------
    BUG REPORT INFORMATION
-------------------------------

**Description**

I want to use the docker image in gitlab-ci and override the entrypoint

**Steps to reproduce the issue:**

1. define a step in gitlab-ci with the docker image : 
```
deploy-tooling-kube:
  stage: deploy-kube
  cache:
    key: "$CI_PIPELINE_ID"
    paths:
      - config
  image:
    name: bitnami/kubectl:1.18
    entrypoint: [ "/bin/bash", "-l", "-c" ]
  script:
    - ls
```
2. run the CI

**Describe the results you received:**

`sh: 3: set: Illegal option -o pipefail`

**Describe the results you expected:**

a success code

**Version**

according to gitlab-ci documentation

```
GitLab Runner uses Docker Engine API v1.25
```

**Comment by juan131** [comment]
Hi @franck-cussac 

I was able to overwrite the default entrypoint without major issues, see:

```console
$ docker run --rm --entrypoint 'bash' bitnami/kubectl -ec 'echo "Hello world"'
Hello world
```

**Comment by franck-cussac** [comment]
Yes I agree, but in gitlab-ci I don't know why I have an error :( Can you test ?

**Comment by juan131** [comment]
Hi @franck-cussac 

I have no GitLab CI environment ready to test it on my side, sorry. Could you try using only `bash` as "entrypoint" moving the rest of flags/arguments to the "script" section?

**Comment by d--j** [comment]
An empty `entrypoint` should work:
```yaml
deploy-tooling-kube:
  stage: deploy-kube
  cache:
    key: "$CI_PIPELINE_ID"
    paths:
      - config
  image:
    name: bitnami/kubectl:1.18
    entrypoint: []
  script:
    - ls
```
