### ISSUE TITLE
Include envsubst

### ISSUE THREAD

**Issue by matiasah** [bitnami/bitnami-docker-kubectl#24]
Hello,

I would like to be able to use the linux command `envsubst` to be able to substitute environment variables into kubernetes chart files. This is so I can use the GitLab Runner commit version in the chart.

Example of a use case is here:
https://stackoverflow.com/questions/65705619/substitute-environment-variable-in-all-files-when-kubectl-apply-ing

Any chances of adding envsubst to this docker image?

**Comment by marcosbc** [comment]
Hi @matiasah, I understand your use case, but I'm not fully clear how that relates to the image itself. Is there any reason for using the `kubectl` image for running non-kubectl commands, instead of using a different image for that purpose?

**Comment by matiasah** [comment]
On my pipeline I can use a single container image for the execution of a job.
```yml
deploy:
  stage: deploy
  image:
    name: bitnami/kubectl:latest
    entrypoint: [""]
  when: manual
  script:
    - kubectl apply -f kubectl/prod/
  dependencies:
    - build
```

I would be forced to create an extra previous job just to put the environment variables that contain the version id of the image into the kubernetes files, which is not ideal because a extra job would take extra time and resources. However if I install it using the scripts, it would still take extra time to install it every time it runs the job.

If that's not enough reason to add envsubst to the Dockerfile, is there any possibility that a secondary image containing envsubst could be provided on Docker Hub?
