### ISSUE TITLE
K8s CronJob

### ISSUE THREAD

**Issue by jiriw-elkjop** [bitnami/bitnami-docker-kubectl#39]
### Name and Version

bitnami/kubectl:latest

### What steps will reproduce the bug?

```yaml
apiVersion: batch/v1beta1
kind: CronJob
metadata:
  name: test
spec:
  concurrencyPolicy: Allow
  failedJobsHistoryLimit: 1
  jobTemplate:
    metadata:
    spec:
      template:
        metadata:
        spec:
          serviceAccount: test
          containers:
          - command: ["sh", "-c"]
            args:
              - kubectl get po --all-namespaces | wc -l;
            image: bitnami/kubectl:latest
            imagePullPolicy: IfNotPresent
            name: cronjob-kubectl
          restartPolicy: Never
          terminationGracePeriodSeconds: 30
  schedule: "*/2 * * * *"
  successfulJobsHistoryLimit: 1
  suspend: false
```

### What is the expected behavior?

No complains related to connection. In this case number of namespaces. 

### What do you see instead?

`The connection to the server 10.0.0.1:443 was refused - did you specify the right host or port?`
